# Generated by Django 4.0.5 on 2022-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_image', models.ImageField(upload_to='')),
                ('detected_class', models.IntegerField()),
                ('detected_default_solution', models.TextField(help_text='detected_default_solution')),
                ('detected_contents', models.TextField(blank=True, help_text='PostContents text', null=True)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solution_images')),
                ('solution_contents', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
