# Generated by Django 4.0.5 on 2022-08-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('id', models.BigAutoField(help_text='PostContents ID', primary_key=True, serialize=False)),
                ('contents', models.TextField(help_text='PostContents text')),
                ('detected_image', models.ImageField(upload_to='detected_images')),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solution_images')),
                ('solution_contents', models.TextField(blank=True, help_text='PostContents text', null=True)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Posts.post')),
            ],
        ),
    ]
