# Generated by Django 4.0.5 on 2022-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detected_default_solution',
            field=models.TextField(help_text='detected_default_solution'),
        ),
    ]
