# Generated by Django 4.0.5 on 2022-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_post_email_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detected_image',
            field=models.URLField(),
        ),
    ]
