# Generated by Django 4.0.5 on 2022-08-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedimagefile',
            name='email',
        ),
        migrations.AddField(
            model_name='detectedimagefile',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
