# Generated by Django 4.0.5 on 2022-08-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='title',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='imagefile',
            table='image',
        ),
    ]
