# Generated by Django 4.0.5 on 2022-08-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_detectedimagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimagefile',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
