# Generated by Django 4.0.5 on 2022-08-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0004_detectedimagefile_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedimagefile',
            name='image',
        ),
        migrations.AddField(
            model_name='detectedimagefile',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
