# Generated by Django 4.0.5 on 2022-08-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0005_remove_detectedimagefile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedimagefile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='detectedimagefile',
            name='image',
            field=models.ImageField(null=True, upload_to='detected'),
        ),
    ]
