# Generated by Django 4.0.5 on 2022-08-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0006_remove_detectedimagefile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedimagefile',
            name='image',
            field=models.ImageField(null=True, upload_to='detected_image'),
        ),
    ]
