# Generated by Django 4.0.5 on 2022-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_id', models.IntegerField()),
                ('solution_default', models.TextField()),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
    ]
