# Generated by Django 4.0.5 on 2022-08-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_id', models.IntegerField()),
                ('solution_deafult', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
    ]
