# Generated by Django 4.0.5 on 2022-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='solution_deafult',
            new_name='solution_default',
        ),
    ]
