# Generated by Django 4.0.5 on 2022-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0002_rename_solution_deafult_solutions_solution_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='solution_default',
            field=models.TextField(),
        ),
    ]
